version: "3.6"

services:
  win-xp:
    container_name: win-xp
    image: qemu-xp
    build: .
    environment:
      - USER=root
      - PASSWORD=password1
    volumes:
      - .:/isos
    ports:
      - 8888:80
